# Generated by Django 5.0.1 on 2024-01-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивация'),
        ),
    ]
