# Generated by Django 5.0.1 on 2024-06-19 04:42

import django.db.models.deletion
import instructions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Произвоодитель')),
                ('slug', models.SlugField(max_length=80, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.brand', verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='FileInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=instructions.models.path_to_file_instuction, verbose_name='Файл')),
                ('instruction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructions.instruction', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'db_table': 'file_instruct',
            },
        ),
    ]
