# Generated by Django 5.0.1 on 2024-01-18 04:00

import django.db.models.deletion
import firmwares.models
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Клиент')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Объект')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
                ('descriiption', models.TextField(verbose_name='Описание файла')),
                ('date_order', models.DateField(verbose_name='Дата заказа')),
                ('date_ready', models.DateField(blank=True, verbose_name='Дата готовности')),
                ('date_check', models.DateField(blank=True, verbose_name='Дата Проверки')),
                ('status', models.IntegerField(choices=[(1, 'Готов'), (2, 'Проверка'), (3, '')], verbose_name='Статус')),
                ('author', models.IntegerField(choices=[(1, 'Мартынов В.')], verbose_name='Автор')),
                ('images', imagekit.models.fields.ProcessedImageField(upload_to='images/product/%y/%m/%d', verbose_name='Основное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SmartRelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=100, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
                ('name', models.IntegerField(choices=[(1, 'ПР200'), (2, 'ПР205'), (3, 'ПР103'), (4, 'SR3B261BD'), (5, 'SR2B201FU'), (6, 'SR2B121FU'), (7, 'Oni')], verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'relay',
                'verbose_name_plural': 'relays',
                'db_table': 'smartrelay',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=firmwares.models.product_images_directory_path, verbose_name='Фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmwares.product', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='relay',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firmwares.smartrelay', verbose_name='Тип ПЛК'),
        ),
    ]
