# Generated by Django 5.0.1 on 2024-01-25 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='level',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='client',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='client',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='subjects',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firmwares.subjects', verbose_name='Объект'),
            preserve_default=False,
        ),
    ]
