# Generated by Django 5.0.1 on 2024-01-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartrelay',
            name='name',
            field=models.CharField(choices=[('ПР200', 'ПР200'), ('ПР205', 'ПР205'), ('ПР103', 'ПР103'), ('SR3B261BD', 'SR3B261BD'), ('SR2B201FU', 'SR2B201FU'), ('SR2B121FU', 'SR2B121FU'), ('Oni', 'Oni')], max_length=20, verbose_name='Модель'),
        ),
    ]
