# Generated by Django 5.0.1 on 2024-01-25 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='subjects',
            new_name='parent',
        ),
    ]
