# Generated by Django 5.0.1 on 2024-01-25 03:42

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0002_rename_subjects_client_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='firmwares.client', verbose_name='Клиент'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='subject',
        ),
        migrations.AddField(
            model_name='product',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firmwares.client', verbose_name='Объект'),
            preserve_default=False,
        ),
    ]
