# Generated by Django 5.0.1 on 2024-01-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0002_alter_smartrelay_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartrelay',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
