# Generated by Django 5.0.1 on 2024-01-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0003_alter_subjects_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='client',
            name='archive',
            field=models.BooleanField(default=True, verbose_name='Архив'),
        ),
        migrations.AddField(
            model_name='product',
            name='archive',
            field=models.BooleanField(default=True, verbose_name='Архив'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='archive',
            field=models.BooleanField(default=True, verbose_name='Архив'),
        ),
    ]
