# Generated by Django 5.0.1 on 2024-01-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0003_alter_smartrelay_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
