# Generated by Django 5.0.1 on 2024-01-26 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0004_remove_product_availability_client_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='firmwares.client', verbose_name='Клиент'),
        ),
    ]
