# Generated by Django 5.0.1 on 2024-01-29 09:02

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0007_alter_product_relay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/product/%y/%m/%d', verbose_name='Основное фото'),
        ),
    ]
