# Generated by Django 5.0.1 on 2024-01-29 09:20

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0008_alter_product_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='subjects',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default=7, upload_to='subjects/%y/%m/%d', verbose_name='Основное фото'),
            preserve_default=False,
        ),
    ]
