# Generated by Django 5.0.1 on 2024-01-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0011_alter_product_date_check_alter_product_date_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='description',
            field=models.TextField(blank=True, default='!', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriiption',
            field=models.TextField(blank=True, default='!', verbose_name='Описание файла'),
        ),
        migrations.AlterField(
            model_name='smartrelay',
            name='name',
            field=models.CharField(choices=[('ПР200', 'ПР200'), ('ПР205', 'ПР205'), ('ПР103', 'ПР103'), ('SR3B261BD', 'SR3B261BD'), ('SR2B261FU', 'SR2B261FU'), ('SR2B201FU', 'SR2B201FU'), ('SR2B121FU', 'SR2B121FU'), ('Oni', 'Oni')], max_length=20, verbose_name='Модель'),
        ),
    ]
