# Generated by Django 5.0.1 on 2024-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0012_subjects_description_alter_product_descriiption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, default='!', verbose_name='Описание'),
        ),
    ]
