# Generated by Django 5.0.1 on 2024-04-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0013_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_product',
            field=models.IntegerField(db_index=True, default=1, verbose_name='ID Продукта'),
            preserve_default=False,
        ),
    ]
