# Generated by Django 5.0.1 on 2024-04-27 07:05

import django.db.models.deletion
import firmwares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0015_alter_product_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_config', models.FileField(upload_to=firmwares.models.product_file_path, verbose_name='Конфигурация')),
                ('file_schema', models.FileField(upload_to=firmwares.models.product_file_path, verbose_name='Схема с описанием')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='firmwares.product', verbose_name='Алгоритм')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'db_table': 'files',
            },
        ),
    ]
