# Generated by Django 5.0.1 on 2024-04-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0016_productfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, default='Данных нет', verbose_name='ОПримечание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriiption',
            field=models.TextField(blank=True, default='Описание отсутствует!', verbose_name='Описание файла'),
        ),
    ]
