# Generated by Django 5.0.1 on 2024-04-27 08:52

import django.db.models.deletion
import firmwares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0017_product_note_alter_product_descriiption'),
        ('users', '0002_profile_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(db_index=True, verbose_name='ID Продукта')),
                ('client', models.CharField(max_length=100, verbose_name='Клиент')),
                ('subject', models.CharField(max_length=100, verbose_name='Объект')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('note', models.TextField(default='Данных нет', verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file_schema', models.FileField(upload_to=firmwares.models.order_file_path, verbose_name='Схема с описанием')),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmwares.smartrelay', verbose_name='Тип ПЛК')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Автор заявки')),
            ],
            options={
                'verbose_name': 'заявку',
                'verbose_name_plural': 'заявки',
                'db_table': 'orders',
            },
        ),
    ]
