# Generated by Django 5.0.1 on 2024-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0018_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reestr',
            field=models.BooleanField(default=False, verbose_name='Реестр'),
        ),
    ]
