# Generated by Django 5.0.1 on 2024-05-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0020_alter_product_status_alter_subjects_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=180, verbose_name='Автор заявки'),
        ),
    ]
