# Generated by Django 5.0.1 on 2024-06-03 08:33

import firmwares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0022_alter_productfile_file_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='file_address_table',
            field=models.FileField(blank=True, null=True, upload_to=firmwares.models.product_file_path, verbose_name='Передача данных'),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, default='Данных нет', verbose_name='Примечание'),
        ),
    ]
