# Generated by Django 5.0.1 on 2024-06-24 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0023_productfile_file_address_table_alter_product_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
