# Generated by Django 5.0.1 on 2024-06-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0024_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
